[package]
name = "solana_contract"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]

[features]
resolution = true
skip-lint = false

[toolchain]
anchor_version = "0.30.1"

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"

[programs.localnet]
solana_contract = "Ef5GU5wYGDREHsv58CqAXTffcQHNGZCGnBHGNcW7riP8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
